@url = http://localhost:5995

### GET ALL JOBS
{{url}}/jobs

### GET SINGLE JOB
{{url}}/jobs/2

### CREATE NEW JOB
POST {{url}}/jobs
content-type: application/json

{
	"id": 1,
	"title": "Frontend Developer TEST",
	"company": "Company Name TEST",
	"url": "http://TEST",
	"description": "test",
	"skillList": "skills TEST",
	"publicationDate": "2022-11-17"
}

### GET ALL SKILLS
{{url}}/skills

### GET SINGLE SKILL
{{url}}/skills/2